// Generated by scripts/build_docs_graph.py -- additive to registry/graph/load.cypher.
// Place these CSVs in Neo4j's import/docs/ subdirectory (or adjust the file:// paths below).

CREATE CONSTRAINT docspec_path IF NOT EXISTS FOR (d:DocSpec) REQUIRE d.path IS UNIQUE;

LOAD CSV WITH HEADERS FROM 'file:///docs/nodes_docspec.csv' AS row
CREATE (:DocSpec {path: row.`path:ID(DocSpec)`, title: row.title});

LOAD CSV WITH HEADERS FROM 'file:///docs/edges_references.csv' AS row
MATCH (a:DocSpec {path: row.`:START_ID(DocSpec)`}), (b:DocSpec {path: row.`:END_ID(DocSpec)`})
CREATE (a)-[:REFERENCES]->(b);
