#!/usr/bin/env python3
"""
Stage 8, Track B -- Neo4j load artifacts. Generates CSV node/edge files plus
a Cypher script using LOAD CSV, from registry/materialized-manifest.json.
Does NOT connect to or load into any database -- this repo has no running
Neo4j instance. Run the emitted load.cypher yourself once you have one (see
registry/graph/README.md, or docs/ for the Raspberry Pi setup guide).

Schema:
  Nodes:  Document, Topic, ConsolidatedDoc, Project, Category
  Edges:  (Document)-[:IN_TOPIC]->(Topic)
          (Topic)-[:CONSOLIDATED_AS]->(ConsolidatedDoc)
          (Document)-[:SUPERSEDED_BY]->(Document)
          (Document)-[:IN_CATEGORY]->(Category)
          (Document)-[:FROM_PROJECT]->(Project)

Usage: python3 scripts/build_neo4j_load.py
"""

import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "registry" / "materialized-manifest.json"
OUT_DIR = REPO_ROOT / "registry" / "graph"


def write_csv(path: Path, fieldnames: list, rows: list):
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)


def main():
    if not MANIFEST_PATH.exists():
        sys.exit("FAIL: registry/materialized-manifest.json not found -- run scripts/build_manifest.py first")

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    docs = manifest["docs"]
    consolidated = json.loads((REPO_ROOT / "registry" / "consolidated-topics.json").read_text(encoding="utf-8"))

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # --- Nodes ---
    document_rows = [
        {
            "path:ID(Document)": path,
            "doc_uuid": rec.get("doc_uuid", ""),
            "dedup_status": rec["dedup_status"],
            "category": rec.get("category", ""),
            "project": rec.get("project", ""),
        }
        for path, rec in docs.items()
    ]
    write_csv(OUT_DIR / "nodes_document.csv", ["path:ID(Document)", "doc_uuid", "dedup_status", "category", "project"], document_rows)

    topic_rows = [{"name:ID(Topic)": name, "doc_count": info["doc_count"]} for name, info in consolidated.items()]
    write_csv(OUT_DIR / "nodes_topic.csv", ["name:ID(Topic)", "doc_count"], topic_rows)

    consolidated_doc_paths = sorted({info["consolidated_doc"] for info in consolidated.values()})
    consolidated_rows = [{"path:ID(ConsolidatedDoc)": p} for p in consolidated_doc_paths]
    write_csv(OUT_DIR / "nodes_consolidateddoc.csv", ["path:ID(ConsolidatedDoc)"], consolidated_rows)

    projects = sorted({rec["project"] for rec in docs.values() if rec.get("project")})
    write_csv(OUT_DIR / "nodes_project.csv", ["name:ID(Project)"], [{"name:ID(Project)": p} for p in projects])

    categories = sorted({rec["category"] for rec in docs.values() if rec.get("category")})
    write_csv(OUT_DIR / "nodes_category.csv", ["name:ID(Category)"], [{"name:ID(Category)": c} for c in categories])

    # --- Edges ---
    in_topic_rows, in_category_rows, from_project_rows, superseded_by_rows = [], [], [], []
    consolidated_as_rows = [
        {":START_ID(Topic)": name, ":END_ID(ConsolidatedDoc)": info["consolidated_doc"]}
        for name, info in consolidated.items()
    ]

    for path, rec in docs.items():
        for t in rec.get("topics", []):
            in_topic_rows.append({":START_ID(Document)": path, ":END_ID(Topic)": t})
        if rec.get("category"):
            in_category_rows.append({":START_ID(Document)": path, ":END_ID(Category)": rec["category"]})
        if rec.get("project"):
            from_project_rows.append({":START_ID(Document)": path, ":END_ID(Project)": rec["project"]})
        for field in ("duplicate_of", "superseded_by"):
            if field in rec:
                target = rec[field].split(" [")[0].strip()
                lookup_key = target[len("knowledge-base/"):] if target.startswith("knowledge-base/") else target
                if lookup_key in docs:
                    superseded_by_rows.append({":START_ID(Document)": path, ":END_ID(Document)": lookup_key, "reason": field})

    write_csv(OUT_DIR / "edges_in_topic.csv", [":START_ID(Document)", ":END_ID(Topic)"], in_topic_rows)
    write_csv(OUT_DIR / "edges_consolidated_as.csv", [":START_ID(Topic)", ":END_ID(ConsolidatedDoc)"], consolidated_as_rows)
    write_csv(OUT_DIR / "edges_in_category.csv", [":START_ID(Document)", ":END_ID(Category)"], in_category_rows)
    write_csv(OUT_DIR / "edges_from_project.csv", [":START_ID(Document)", ":END_ID(Project)"], from_project_rows)
    write_csv(OUT_DIR / "edges_superseded_by.csv", [":START_ID(Document)", ":END_ID(Document)", "reason"], superseded_by_rows)

    cypher = """// Generated by scripts/build_neo4j_load.py -- run against an empty database.
// Place the sibling *.csv files in Neo4j's import/ directory first (see registry/graph/README.md).

CREATE CONSTRAINT document_path IF NOT EXISTS FOR (d:Document) REQUIRE d.path IS UNIQUE;
CREATE CONSTRAINT topic_name IF NOT EXISTS FOR (t:Topic) REQUIRE t.name IS UNIQUE;
CREATE CONSTRAINT consolidateddoc_path IF NOT EXISTS FOR (c:ConsolidatedDoc) REQUIRE c.path IS UNIQUE;
CREATE CONSTRAINT project_name IF NOT EXISTS FOR (p:Project) REQUIRE p.name IS UNIQUE;
CREATE CONSTRAINT category_name IF NOT EXISTS FOR (c:Category) REQUIRE c.name IS UNIQUE;

LOAD CSV WITH HEADERS FROM 'file:///nodes_document.csv' AS row
CREATE (:Document {path: row.`path:ID(Document)`, doc_uuid: row.doc_uuid, dedup_status: row.dedup_status, category: row.category, project: row.project});

LOAD CSV WITH HEADERS FROM 'file:///nodes_topic.csv' AS row
CREATE (:Topic {name: row.`name:ID(Topic)`, doc_count: toInteger(row.doc_count)});

LOAD CSV WITH HEADERS FROM 'file:///nodes_consolidateddoc.csv' AS row
CREATE (:ConsolidatedDoc {path: row.`path:ID(ConsolidatedDoc)`});

LOAD CSV WITH HEADERS FROM 'file:///nodes_project.csv' AS row
CREATE (:Project {name: row.`name:ID(Project)`});

LOAD CSV WITH HEADERS FROM 'file:///nodes_category.csv' AS row
CREATE (:Category {name: row.`name:ID(Category)`});

LOAD CSV WITH HEADERS FROM 'file:///edges_in_topic.csv' AS row
MATCH (d:Document {path: row.`:START_ID(Document)`}), (t:Topic {name: row.`:END_ID(Topic)`})
CREATE (d)-[:IN_TOPIC]->(t);

LOAD CSV WITH HEADERS FROM 'file:///edges_consolidated_as.csv' AS row
MATCH (t:Topic {name: row.`:START_ID(Topic)`}), (c:ConsolidatedDoc {path: row.`:END_ID(ConsolidatedDoc)`})
CREATE (t)-[:CONSOLIDATED_AS]->(c);

LOAD CSV WITH HEADERS FROM 'file:///edges_in_category.csv' AS row
MATCH (d:Document {path: row.`:START_ID(Document)`}), (c:Category {name: row.`:END_ID(Category)`})
CREATE (d)-[:IN_CATEGORY]->(c);

LOAD CSV WITH HEADERS FROM 'file:///edges_from_project.csv' AS row
MATCH (d:Document {path: row.`:START_ID(Document)`}), (p:Project {name: row.`:END_ID(Project)`})
CREATE (d)-[:FROM_PROJECT]->(p);

LOAD CSV WITH HEADERS FROM 'file:///edges_superseded_by.csv' AS row
MATCH (d1:Document {path: row.`:START_ID(Document)`}), (d2:Document {path: row.`:END_ID(Document)`})
CREATE (d1)-[:SUPERSEDED_BY {reason: row.reason}]->(d2);
"""
    (OUT_DIR / "load.cypher").write_text(cypher, encoding="utf-8")

    readme = f"""# Neo4j Load Artifacts

Generated by `scripts/build_neo4j_load.py` from `registry/materialized-manifest.json`.
Never auto-loaded -- this repo has no running Neo4j instance. To load:

1. Copy all `*.csv` files in this directory into your Neo4j server's `import/` directory
   (on a fresh install this is usually `/var/lib/neo4j/import/` or, for Docker, whatever
   you bind-mounted to `/var/lib/neo4j/import`).
2. Open `cypher-shell` or the Neo4j Browser and run the contents of `load.cypher`.
3. Sanity check: `MATCH (n) RETURN count(n);` should return {len(document_rows) + len(topic_rows) + len(consolidated_doc_paths) + len(projects) + len(categories)}.

See the Raspberry Pi setup guide for how to stand up the instance itself if you don't have one.

## Known gap

Only direct-match `duplicate_of`/`superseded_by` pointers become edges here ({len(superseded_by_rows)}
of 74 superseded docs). 13 docs have either a bare filename recorded relative to their category
directory rather than the repo root, or a legitimate multi-hop revision chain (see
`scripts/check_drift.py`, which resolves all 74 correctly by following those chains) -- this script
doesn't yet reuse that resolution logic, so those 13 SUPERSEDED_BY edges are missing rather than wrong.
Safe to add later by importing `resolve_pointer` from `check_drift.py`.

## Example queries once loaded

Everything that touches both a topic and a project:
```cypher
MATCH (d:Document)-[:IN_TOPIC]->(t:Topic), (d)-[:FROM_PROJECT]->(p:Project)
RETURN t.name, p.name, count(d) ORDER BY count(d) DESC;
```

Every document a given consolidated doc's topic absorbed:
```cypher
MATCH (c:ConsolidatedDoc {{path: 'docs/DC-DION-RECONCILED-001.md'}})<-[:CONSOLIDATED_AS]-(t:Topic)<-[:IN_TOPIC]-(d:Document)
RETURN d.path;
```

The full supersession chain for a doc:
```cypher
MATCH path = (d:Document {{path: '...'}})-[:SUPERSEDED_BY*]->(canonical:Document)
RETURN path;
```
"""
    (OUT_DIR / "README.md").write_text(readme, encoding="utf-8")

    print(f"Wrote node/edge CSVs, load.cypher, and README.md to {OUT_DIR.relative_to(REPO_ROOT)}/")
    print(f"  {len(document_rows)} Document, {len(topic_rows)} Topic, {len(consolidated_doc_paths)} ConsolidatedDoc, {len(projects)} Project, {len(categories)} Category nodes")
    print(f"  {len(in_topic_rows)} IN_TOPIC, {len(consolidated_as_rows)} CONSOLIDATED_AS, {len(in_category_rows)} IN_CATEGORY, {len(from_project_rows)} FROM_PROJECT, {len(superseded_by_rows)} SUPERSEDED_BY edges")


if __name__ == "__main__":
    main()
