#!/usr/bin/env python3
"""
Stage 8b -- Obsidian graph + Neo4j load artifacts for docs/*.md, the
counterpart to build_obsidian_graph.py / build_neo4j_load.py that only ever
covered knowledge-base/. Reads registry/docs-manifest.json (from
build_docs_manifest.py) and:

  1. Upserts a "Related (auto-generated)" [[wikilink]] block into each
     docs/*.md file, same idempotent marker convention as Stage 8 Track A --
     safe to re-run any time you add or edit a docs/*.md file.
  2. Emits Document nodes + REFERENCES edges as CSV + a load.cypher fragment
     under registry/graph/docs/, additive to (does not overwrite) the
     knowledge-base/ graph artifacts already in registry/graph/.

Usage: python3 scripts/build_docs_manifest.py && python3 scripts/build_docs_graph.py
"""

import csv
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"
MANIFEST_PATH = REPO_ROOT / "registry" / "docs-manifest.json"
OUT_DIR = REPO_ROOT / "registry" / "graph" / "docs"

START_MARKER = "<!-- AUTO-GENERATED RELATED START (scripts/build_docs_graph.py) -->"
END_MARKER = "<!-- AUTO-GENERATED RELATED END -->"
BLOCK_RE = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n?", re.DOTALL)


def wikilink(filename: str, display: str) -> str:
    stem = filename[:-3] if filename.endswith(".md") else filename
    return f"[[{stem}|{display}]]"


def build_related_block(name: str, rec: dict, docs: dict) -> str:
    lines = [START_MARKER, "", "## Related (auto-generated)", ""]

    if rec["references"]:
        lines.append("**References:**")
        for target in rec["references"]:
            lines.append(f"- {wikilink(target, docs[target]['title'])}")
        lines.append("")

    if rec["referenced_by"]:
        lines.append("**Referenced by:**")
        for source in rec["referenced_by"]:
            lines.append(f"- {wikilink(source, docs[source]['title'])}")
        lines.append("")

    if not rec["references"] and not rec["referenced_by"]:
        lines.append("*No cross-references detected to/from other docs/*.md files.*")
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def upsert_block(path: Path, block: str) -> bool:
    text = path.read_text(encoding="utf-8", errors="replace")
    if BLOCK_RE.search(text):
        new_text = BLOCK_RE.sub(block, text)
    else:
        sep = "" if text.endswith("\n\n") else ("\n\n" if text.endswith("\n") else "\n\n")
        new_text = text + sep + block
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")
        return True
    return False


def write_csv(path: Path, fieldnames: list, rows: list):
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)


def main():
    if not MANIFEST_PATH.exists():
        sys.exit("FAIL: registry/docs-manifest.json not found -- run scripts/build_docs_manifest.py first")

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    docs = manifest["docs"]

    updated = 0
    for name, rec in docs.items():
        block = build_related_block(name, rec, docs)
        if upsert_block(DOCS_DIR / name, block):
            updated += 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    node_rows = [{"path:ID(DocSpec)": name, "title": rec["title"]} for name, rec in docs.items()]
    write_csv(OUT_DIR / "nodes_docspec.csv", ["path:ID(DocSpec)", "title"], node_rows)

    edge_rows = [
        {":START_ID(DocSpec)": name, ":END_ID(DocSpec)": target}
        for name, rec in docs.items()
        for target in rec["references"]
    ]
    write_csv(OUT_DIR / "edges_references.csv", [":START_ID(DocSpec)", ":END_ID(DocSpec)"], edge_rows)

    cypher = f"""// Generated by scripts/build_docs_graph.py -- additive to registry/graph/load.cypher.
// Place these CSVs in Neo4j's import/docs/ subdirectory (or adjust the file:// paths below).

CREATE CONSTRAINT docspec_path IF NOT EXISTS FOR (d:DocSpec) REQUIRE d.path IS UNIQUE;

LOAD CSV WITH HEADERS FROM 'file:///docs/nodes_docspec.csv' AS row
CREATE (:DocSpec {{path: row.`path:ID(DocSpec)`, title: row.title}});

LOAD CSV WITH HEADERS FROM 'file:///docs/edges_references.csv' AS row
MATCH (a:DocSpec {{path: row.`:START_ID(DocSpec)`}}), (b:DocSpec {{path: row.`:END_ID(DocSpec)`}})
CREATE (a)-[:REFERENCES]->(b);
"""
    (OUT_DIR / "load.cypher").write_text(cypher, encoding="utf-8")

    readme = f"""# docs/*.md Graph Artifacts (Stage 8b)

Generated by `scripts/build_docs_graph.py` from `registry/docs-manifest.json`.
Additive to the knowledge-base/ graph in `registry/graph/` (Stage 8 Track A/B) --
a separate node label (`DocSpec` vs `Document`) so the two never collide if both
get loaded into the same Neo4j instance.

1. Run `python3 scripts/build_docs_manifest.py` after adding or editing any
   `docs/*.md` file, then `python3 scripts/build_docs_graph.py`.
2. Copy this directory's CSVs into Neo4j's `import/docs/` and run `load.cypher`.
3. Sanity check: `MATCH (n:DocSpec) RETURN count(n);` should return {len(node_rows)}.

## Example query

Everything a given doc extends or is extended by:
```cypher
MATCH (d:DocSpec {{path: 'DC-COMPUTE-SILICON-ARCH-001.md'}})-[:REFERENCES]-(other)
RETURN other.path, other.title;
```
"""
    (OUT_DIR / "README.md").write_text(readme, encoding="utf-8")

    print(f"Updated {updated} docs/*.md files with a Related block.")
    print(f"Wrote {len(node_rows)} DocSpec nodes, {len(edge_rows)} REFERENCES edges to {OUT_DIR.relative_to(REPO_ROOT)}/")


if __name__ == "__main__":
    main()
