#!/usr/bin/env python3
"""
Stage 7 item #1 -- rebuild knowledge-base/_INDEX.md.

The existing file is frozen at Stage 3 (category/project counts only). This
regenerates it from registry/materialized-manifest.json (build_manifest.py
must be run first), keeping the category table and adding three new sections:
dedup status, topic-cluster coverage, and Stage 6 consolidator output.

Usage: python3 scripts/rebuild_index.py
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
KB_DIR = REPO_ROOT / "knowledge-base"
DOCS_DIR = REPO_ROOT / "docs"
MANIFEST_PATH = REPO_ROOT / "registry" / "materialized-manifest.json"
OUT_PATH = KB_DIR / "_INDEX.md"


def main():
    if not MANIFEST_PATH.exists():
        sys.exit("FAIL: registry/materialized-manifest.json not found -- run scripts/build_manifest.py first")

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    docs = manifest["docs"]
    counts = manifest["counts"]

    by_category = defaultdict(lambda: {"count": 0, "projects": set()})
    for rec in docs.values():
        if rec["dedup_status"] == "superseded":
            continue  # category table describes the live tree, matching the original Stage 3 table
        by_category[rec["category"]]["count"] += 1
        if rec["project"]:
            by_category[rec["category"]]["projects"].add(rec["project"])

    category_rows = "\n".join(
        f"| `{cat}` | {info['count']} | {len(info['projects'])} |"
        for cat, info in sorted(by_category.items())
    )

    topic_registry_files = {Path(v["consolidated_doc"]).name for v in json.loads(
        (REPO_ROOT / "registry" / "consolidated-topics.json").read_text(encoding="utf-8")
    ).values()}
    all_reconciled_on_disk = sorted(p.name for p in DOCS_DIR.glob("DC-*-RECONCILED-*.md"))
    topic_reconciled = [n for n in all_reconciled_on_disk if n in topic_registry_files]
    pre_registry_reconciled = [n for n in all_reconciled_on_disk if n not in topic_registry_files]
    other_docs_on_disk = sorted(
        p.name for p in DOCS_DIR.glob("*.md")
        if not (p.name.startswith("DC-") and "RECONCILED" in p.name)
    )

    lines = [
        "# Knowledge Base — Materialized Index (Stages 3-6)",
        "",
        "Regenerated by `scripts/rebuild_index.py` from `registry/materialized-manifest.json` "
        "(itself built by `scripts/build_manifest.py` from `_kb_doc_classified.jsonl`, `_topics.md`, "
        "and `registry/consolidated-topics.json`). Don't hand-edit -- rerun the two scripts instead.",
        "",
        "## Stage 3 — classification (live docs only, excludes `_superseded/`)",
        "",
        "| Category | Doc count | Projects |",
        "|---|---|---|",
        category_rows,
        "",
        "## Stage 4 — dedup / status",
        "",
        f"- **{counts['canonical']}** canonical (live, no dedup issue)",
        f"- **{counts['superseded']}** superseded (moved to a `_superseded/` subfolder, each with a `duplicate_of`/`superseded_by` pointer verified by `scripts/check_drift.py`)",
        f"- **{counts['disputed']}** disputed (`status: disputed` — a genuine \"no basis to prefer one\" case per DC-DEDUP-STD-001 §4, left in place rather than forced)",
        f"- **{counts['total_docs']}** total docs tracked",
        "",
        "## Stage 5 — topic clusters",
        "",
        f"- **{counts['topics']}** confirmed topics in [`_topics.md`](./_topics.md)",
        f"- **{counts['docs_in_at_least_one_topic']}** canonical docs belong to at least one topic "
        f"({counts['topic_memberships']} total topic memberships — "
        f"{counts['topic_memberships'] - counts['docs_in_at_least_one_topic']} docs are deliberately cross-listed in more than one topic; see each doc's `consolidated_into` field)",
        f"- **{counts['ungrouped']}** canonical docs correctly left ungrouped (no other doc shares their subject closely enough to cluster)",
        "",
        "## Stage 6 — consolidator output",
        "",
        f"- **{len(topic_reconciled)}** `DC-*-RECONCILED-*.md` documents tied to a confirmed Stage 5 topic in [`docs/`](../docs/) — see `registry/consolidated-topics.json` for the topic → doc mapping",
        f"- **{len(pre_registry_reconciled)}** more `DC-*-RECONCILED-*.md` document(s) predate the topic-registry-driven process ({', '.join(pre_registry_reconciled)}) — a one-off consolidation done before `registry/consolidated-topics.json` existed, not tied to any of the 80 topics",
        f"- **{len(other_docs_on_disk)}** other standalone documents also live in `docs/` (pre-pipeline reference docs, conversation-artifact extractions such as `DC-LKB-*`/`DC-SIM-*`, and later additions not produced by this pipeline)",
        "",
        "## Provenance chain, per document",
        "",
        "Every live doc's own front matter now carries the full chain: `topic:` (Stage 5) → "
        "`consolidated_into:` (Stage 6, added by `scripts/add_consolidated_into.py`). Every "
        "superseded doc's front matter carries `status`, `duplicate_of`/`superseded_by`, and a reason "
        "(Stage 4). See `registry/materialized-manifest.json` for the same information in one "
        "machine-readable file, keyed by path.",
        "",
    ]

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
