// Generated by scripts/build_neo4j_load.py -- run against an empty database.
// Place the sibling *.csv files in Neo4j's import/ directory first (see registry/graph/README.md).

CREATE CONSTRAINT document_path IF NOT EXISTS FOR (d:Document) REQUIRE d.path IS UNIQUE;
CREATE CONSTRAINT topic_name IF NOT EXISTS FOR (t:Topic) REQUIRE t.name IS UNIQUE;
CREATE CONSTRAINT consolidateddoc_path IF NOT EXISTS FOR (c:ConsolidatedDoc) REQUIRE c.path IS UNIQUE;
CREATE CONSTRAINT project_name IF NOT EXISTS FOR (p:Project) REQUIRE p.name IS UNIQUE;
CREATE CONSTRAINT category_name IF NOT EXISTS FOR (c:Category) REQUIRE c.name IS UNIQUE;

LOAD CSV WITH HEADERS FROM 'file:///nodes_document.csv' AS row
CREATE (:Document {path: row.`path:ID(Document)`, doc_uuid: row.doc_uuid, dedup_status: row.dedup_status, category: row.category, project: row.project});

LOAD CSV WITH HEADERS FROM 'file:///nodes_topic.csv' AS row
CREATE (:Topic {name: row.`name:ID(Topic)`, doc_count: toInteger(row.doc_count)});

LOAD CSV WITH HEADERS FROM 'file:///nodes_consolidateddoc.csv' AS row
CREATE (:ConsolidatedDoc {path: row.`path:ID(ConsolidatedDoc)`});

LOAD CSV WITH HEADERS FROM 'file:///nodes_project.csv' AS row
CREATE (:Project {name: row.`name:ID(Project)`});

LOAD CSV WITH HEADERS FROM 'file:///nodes_category.csv' AS row
CREATE (:Category {name: row.`name:ID(Category)`});

LOAD CSV WITH HEADERS FROM 'file:///edges_in_topic.csv' AS row
MATCH (d:Document {path: row.`:START_ID(Document)`}), (t:Topic {name: row.`:END_ID(Topic)`})
CREATE (d)-[:IN_TOPIC]->(t);

LOAD CSV WITH HEADERS FROM 'file:///edges_consolidated_as.csv' AS row
MATCH (t:Topic {name: row.`:START_ID(Topic)`}), (c:ConsolidatedDoc {path: row.`:END_ID(ConsolidatedDoc)`})
CREATE (t)-[:CONSOLIDATED_AS]->(c);

LOAD CSV WITH HEADERS FROM 'file:///edges_in_category.csv' AS row
MATCH (d:Document {path: row.`:START_ID(Document)`}), (c:Category {name: row.`:END_ID(Category)`})
CREATE (d)-[:IN_CATEGORY]->(c);

LOAD CSV WITH HEADERS FROM 'file:///edges_from_project.csv' AS row
MATCH (d:Document {path: row.`:START_ID(Document)`}), (p:Project {name: row.`:END_ID(Project)`})
CREATE (d)-[:FROM_PROJECT]->(p);

LOAD CSV WITH HEADERS FROM 'file:///edges_superseded_by.csv' AS row
MATCH (d1:Document {path: row.`:START_ID(Document)`}), (d2:Document {path: row.`:END_ID(Document)`})
CREATE (d1)-[:SUPERSEDED_BY {reason: row.reason}]->(d2);
